---
references:
  - "File: /app/src/main/java/intro/Point.java"
generationTime: 2026-08-12T11:59:48.652Z
---
classDiagram
    class Point {
        - int x
        - int y
        + Point(int, int)
        + getX() int
        + getY() int
    }