/*
 * This source file was generated by the Gradle 'init' task
 */
package intro;

import static org.junit.jupiter.api.Assertions.assertEquals;

import org.junit.jupiter.api.Test;

class AppTest {
    @Test
    void appHasAGreeting() {
        assertEquals(1 + 1, 2, "1 + 1 should equal 2");
    }
}
